name       : python-patsy
version    : 0.5.1
release    : 5
source     :
    - https://pypi.io/packages/source/p/patsy/patsy-0.5.1.tar.gz : f115cec4201e1465cd58b9866b0b0e7b941caafec129869057405bfe5b5e3991
homepage   : https://github.com/pydata/patsy
license    : BSD-2-Clause
component  : programming.python
summary    : Python package for describing statistical models and building design
    matrices
description: |
    patsy is a Python package for describing statistical models (especially linear models, or models that have a linear component) and building design matrices. It is closely inspired by and compatible with the formula mini-language used in R and S.
builddeps  :
    - numpy
    - python-nose
rundeps    :
    - python-six
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test nosetests-%python3_version%
