name       : python-patsy
version    : 0.5.2
release    : 6
source     :
    - https://pypi.io/packages/source/p/patsy/patsy-0.5.2.tar.gz : 5053de7804676aba62783dbb0f23a2b3d74e35e5bfa238b88b7cbf148a38b69d
homepage   : https://github.com/pydata/patsy
license    : BSD-2-Clause
component  : programming.python
summary    : Python package for describing statistical models and building design matrices
description: |
    patsy is a Python package for describing statistical models (especially linear models, or models that have a linear component) and building design matrices. It is closely inspired by and compatible with the formula mini-language used in R and S.
builddeps  :
    - numpy
    - python-nose # check
    - python-pytest # check
rundeps    :
    - python-six
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test nosetests-%python3_version%
