name       : python-patsy
version    : 0.5.3
release    : 8
source     :
    - https://pypi.io/packages/source/p/patsy/patsy-0.5.3.tar.gz : bdc18001875e319bc91c812c1eb6a10be4bb13cb81eb763f466179dca3b67277
homepage   : https://github.com/pydata/patsy
license    : BSD-2-Clause
component  : programming.python
summary    : Python package for describing statistical models and building design matrices
description: |
    patsy is a Python package for describing statistical models (especially linear models, or models that have a linear component) and building design matrices. It is closely inspired by and compatible with the formula mini-language used in R and S.
builddeps  :
    - numpy
    - python-nose # check
    - python-pytest # check
rundeps    :
    - python-six
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test nosetests-%python3_version%
